name: me_and_flora
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  equatable: ^2.0.0
  auto_route: '7.8.4'
  auto_route_generator: ^7.3.2
  iconsax_flutter: ^1.0.0
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  get_it: ^7.2.0
  dio: ^5.4.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  intl: ^0.18.0
  calendar_date_picker2: ^0.5.5
  flutter_data_table: ^1.0.2
  appmetrica_plugin: ^2.0.0
  get_ip_address: ^0.0.6
  flutter_secure_storage: ^4.2.1
  dio_interceptor_plus: ^0.0.2
  retrofit: ^4.1.0
  logger: any  #for logging purpose
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.9
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  retrofit_generator: '>=7.0.0 <8.0.0'
  analyzer: ^6.2.0

flutter_native_splash:
  color: "#090E05"
  image: assets/images/logo.png
  android: true
  ios: false
  web: false

flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Reem_Kufi
      fonts:
        - asset: assets/fonts/Reem_Kufi/ReemKufi-Regular.ttf
          weight: 400
        - asset: assets/fonts/Reem_Kufi/ReemKufi-Medium.ttf
          weight: 500
        - asset: assets/fonts/Reem_Kufi/ReemKufi-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Reem_Kufi/ReemKufi-Bold.ttf
          weight: 700
