spring:
  application:
    name: MainServer
  version: 1.1
  profiles:
    include: hidden
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/MeAndFlora
    username: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
  error-messages:
    badlogin: badlogin
    badpassword: badpassword
    badip: badip
    usrnotfound: usrnotfound
    sessionidproblem: sessionidproblem
    doublelogin: doublelogin

docker:
  login: bladway

