server:
  ssl:
    key-store: ${MAINSERVER_SSL_PATH}
    key-store-type: PKCS12
    key-store-password: ${MAINSERVER_SSL_PASSWORD}
  port: ${MAINSERVER_PORT}
logging:
  level:
    '[org.springframework.security]': trace
  file:
    name: MainServer.log
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database: postgresql
auth:
  badlogin: badlogin
  badpassword: badpassword
  badip: badip
  usrnotfound: usrnotfound
  sessionidproblem: sessionidproblem
  doublelogin: doublelogin
jwt:
  password: ${MAINSERVER_JWT_PASSWORD}
  passwordr: ${MAINSERVER_JWR_R_PASSWORD}
  lifetime: ${MAINSERVER_JWT_LIFETIME}
  lifetimer: ${MAINSERVER_JWT_R_LIFETIME}
  expired: expired
  expiredr: expiredr
  badjwt: badjwt
  badjwtr: badjwtr
rights:
  norights: norights
images:
  path: ${MAINSERVER_IMAGES_PATH}