version: "3.8"

services:

  postgres:
    image: postgres:16.2
    container_name: MeAndFlora-Database
    hostname: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=MeAndFlora
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=${PG_PASSWORD}
    volumes:
      - MeAndFlora-Database:/var/lib/postgresql/data
      
  redis:
    image: bitnami/redis:7.2.4
    container_name: MeAndFlora-Cachebase
    hostname: redis
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_PORT_NUMBER=6379
      - REDIS_PASSWORD=${RS_PASSWORD}
      - ALLOW_EMPTY_PASSWORD=no
    volumes:
      - MeAndFlora-Cachebase:/bitnami/redis/data

  zookeeper:
    image: zookeeper:3.9.2
    container_name: MeAndFlora-Zookeeper
    hostname: zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: MeAndFlora-Kafka
    hostname: kafka
    restart: always
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: OUTSIDE://${VM_HAMACHI_IP}:9092,LOCAL://localhost:9093,CONTAINERS://kafka:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: OUTSIDE:PLAINTEXT,LOCAL:PLAINTEXT,CONTAINERS:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: CONTAINERS
      # KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      # KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      # KAFKA_TOOLS_LOG4J_LOGLEVEL: ERROR
      # KAFKA_LOG4J_LOGGERS: org.apache.zookeeper=ERROR, org.apache.kafka=ERROR, kafka=ERROR, kafka.cluster=ERROR, kafka.controller=ERROR, kafka.coordinator=ERROR, kafka.log=ERROR, kafka.server=ERROR, kafka.zookeeper=ERROR, state.change.logger=ERROR
    depends_on:
      - zookeeper

  MainServer:
    image: bladway/maf-mainserver
    container_name: MeAndFlora-MainServer
    hostname: MainServer
    restart: always
    ports:
      - "8080:8080"

volumes:
  MeAndFlora-Database:
    name: MeAndFlora-Database
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /server/MeAndFlora-Database
  MeAndFlora-Cachebase:
    name: MeAndFlora-Cachebase
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /server/MeAndFlora-Cachebase