version: "3.8"

services:

  postgres:
    image: postgres:16.2-alpine
    container_name: MeAndFlora-Database
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=MeAndFlora
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=tyesl124
    volumes:
      - MeAndFlora-Database:/var/lib/postgresql/data
      
  redis:
    image: redis:7.2.4-alpine
    container_name: MeAndFlora-Cachebase
    restart: always
    ports:
      - "6379:6379"
    environment:
      - REDIS_DATABASES=16
      - REDIS_PASSWORD=tyesl124
      - REDIS_PORT=6379
    volumes:
      - MeAndFlora-Cachebase:/data
    # command: ["redis-server", "--bind", "0.0.0.0"]

  zookeeper:
    image: zookeeper:3.9.2
    container_name: MeAndFlora-Zookeeper
    restart: always
    ports:
      - "2181:2181"
    environment:
      ALLOW_ANONYMOUS_LOGIN: yes

  kafka:
    image: bitnami/kafka:3.4.1
    container_name: MeAndFlora-Kafka
    restart: always
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 25.41.235.94:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      ALLOW_PLAINTEXT_LISTENERS: yes
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper

volumes:
  MeAndFlora-Database:
    name: MeAndFlora-Database
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /server/MeAndFlora-Database
  MeAndFlora-Cachebase:
    name: MeAndFlora-Cachebase
    driver: local
    driver_opts: 
      type: none
      o: bind
      device: /server/MeAndFlora-Cachebase